#!/bin/bash

wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
sudo dpkg -i crowdin.deb

sudo apt-get install apache2
sudo service apache2 start

sudo apt-get install -y docker docker.io python3-venv python3-sphinx unzip zip

mkdir -p /ephemeral/crowdin
cd /ephemeral/crowdin

git clone git@github.com:holatuwol/github-crowdin-crontab.git

git clone git@github.com:holatuwol/liferay-docs.git
cd liferay-docs
git remote add upstream git@github.com:liferay/liferay-docs.git
cd -

git clone git@github.com:holatuwol/liferay-learn.git
cd liferay-learn
git remote add upstream git@github.com:liferay/liferay-learn.git
cd -

git clone git@github.com:holatuwol/zendesk-articles.git

# Need to configure (via git config --global) crowdin information

## crowdin.login
## crowdin.password
## crowdin.api-key.liferay-documentation

# Need to configure (via git config --global) zendesk information
# https://developer.zendesk.com/requests/new

## liferay-support.zendesk.com.token

# Need to manually add a job to your crontab

## 0 20 * * * /ephemeral/crowdin/github-crowdin-crontab/ec2translate | tee /home/ubuntu/translate.txt